name: grade12_exam_prep_tutor
description: A cross-platform Flutter app for 12th-grade exam preparation.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  google_sign_in: ^7.1.1
  sqflite: ^2.3.2
  path: ^1.8.3
  syncfusion_flutter_pdf: ^24.1.41
  archive: ^4.0.7
  xml: ^6.5.0
  file_picker: ^6.1.1
  awesome_notifications: ^0.10.1
  flare_flutter: ^3.0.2
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  flutter_colorpicker: ^1.1.0
  # State management
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
