name: grade12_exam_prep_tutor
description: A cross-platform Flutter app for 12th-grade exam preparation.
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  sqflite: ^2.3.2
  path: ^1.8.3
  syncfusion_flutter_pdf: ^31.1.19
  archive: ^4.0.7
  xml: ^6.5.0
  file_picker: ^10.3.3
  pdfx: ^2.9.2
  flutter_local_notifications: ^15.0.0
  confetti: ^0.7.0
  awesome_notifications: ^0.10.1
  flare_flutter: ^3.0.2
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^4.0.0
  timezone: ^0.9.4
  flutter_colorpicker: ^1.1.0
  # State management
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http: ^1.2.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
