// Placeholder Firebase options. Replace these values by running
// `flutterfire configure` or copying the generated `DefaultFirebaseOptions`
// from the FlutterFire CLI. This file is intentionally a placeholder so
// the app compiles and the guarded initialization in `main.dart` can import
// this symbol. Replace all `REPLACE_WITH_*` values with your project's
// configuration.

// Generated by flutterfire configure for Android (kuraz-app).
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not supported in this configuration.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ0U0dJm73uvWFdb3OPPUflnwbeuYicGI',
    appId: '1:445070976852:android:67a452cf03a9fff9834ac1',
    messagingSenderId: '445070976852',
    projectId: 'kuraz-app',
    storageBucket: 'kuraz-app.firebasestorage.app',
  );

}