import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'theme/app_theme.dart';
import 'screens/auth_screen.dart';
import 'screens/home_dashboard_screen.dart';
import 'screens/upload_screen.dart';
import 'screens/plan_builder_screen.dart';
import 'screens/flashcard_screen.dart';
import 'screens/exam_screen.dart';
import 'screens/public_plans_screen.dart';
import 'screens/progress_screen.dart';
import 'screens/settings_screen.dart';
import 'package:flutter/foundation.dart';
import 'providers/auth_state.dart';
import 'providers/settings_state.dart';
import 'services/notification_service.dart';
import 'services/local_sync_service.dart';
import 'services/firebase_auth_service.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/study_plan.dart';

class InitializationErrorScreen extends StatelessWidget {
  final VoidCallback onRetry;

  const InitializationErrorScreen({super.key, required this.onRetry});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('Initialization Error')),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Text('Failed to initialize the app. Please check your network or configuration.'),
                const SizedBox(height: 16),
                ElevatedButton(onPressed: onRetry, child: const Text('Retry')),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Hive for StudyPlan persistence. This must run before opening boxes.
  await Hive.initFlutter();
  // Register adapters generated by build_runner.
  if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(StudyPlanAdapter());
  if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(FlashcardAdapter());
  if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(SubtopicAdapter());
  // Ensure the box is available early so screens can read/write.
  await Hive.openBox<StudyPlan>('studyPlans');
  bool firebaseOk = false;
  try {
    // Prevent duplicate initialization (fires on hot restart or if another
    // part of the app already initialized Firebase). See https://firebase.
    // google.com/docs/reference/android/com/google/firebase/FirebaseApp for
    // background. This avoids the [core/duplicate-app] error.
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }
    firebaseOk = true;
  } catch (e, st) {
    // Log to console for debugging; consider reporting to Sentry or similar.
    // If the native Android side already initialized Firebase (for example
    // via the Google Services plugin), the SDK may throw a duplicate-app
    // error. Treat that as success so the Flutter app continues.
    if (e is FirebaseException && e.code == 'duplicate-app') {
      firebaseOk = true;
      if (kDebugMode) print('Firebase already initialized (duplicate-app) — continuing.');
    } else {
      if (kDebugMode) {
        print('Firebase initialization error: $e');
        print(st);
      }
    }
  }

  // Initialize local notification service once Firebase (and platform) are ready.
  if (firebaseOk) {
    try {
      await DefaultNotificationService().init();
      if (kDebugMode) print('NotificationService initialized');
    } catch (e) {
      if (kDebugMode) print('NotificationService init failed: $e');
    }
    // Start connectivity listener for local sync if a user is already signed in.
    try {
      final user = AuthService().currentUser;
      if (user != null) {
        LocalSyncService().startConnectivityListener(user.uid);
      }
    } catch (e) {
      if (kDebugMode) print('Failed to start LocalSyncService listener: $e');
    }
  }

  runApp(MyApp(firebaseOk: firebaseOk));
}

class MyApp extends StatelessWidget {
  final bool firebaseOk;

  const MyApp({super.key, required this.firebaseOk});

  @override
  Widget build(BuildContext context) {
    if (!firebaseOk) {
      // Show a minimal retry screen when initialization fails.
      return InitializationErrorScreen(
        onRetry: () async {
          // A simple retry action: try initializing Firebase again and restart the app.
          try {
            if (Firebase.apps.isEmpty) {
              await Firebase.initializeApp(
                options: DefaultFirebaseOptions.currentPlatform,
              );
            }
            // If successful, force a rebuild by using Navigator to push replacement.
            // In a larger app you might use better state management to reflect this.
            runApp(const MyApp(firebaseOk: true));
          } catch (e) {
            if (kDebugMode) print('Retry failed: $e');
          }
        },
      );
    }

    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthState()),
        ChangeNotifierProvider(create: (_) => SettingsState()),
      ],
      child: MaterialApp(
        title: 'Grade12 Exam Prep Tutor',
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        home: Builder(builder: (context) {
          // If Firebase initialized at app startup, wire the auth stream. Otherwise
          // fall back to the local AuthState provider to allow widget tests and
          // non-Firebase environments to run.
          if (firebaseOk) {
            return StreamBuilder(
              stream: FirebaseAuth.instance.authStateChanges(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Scaffold(body: Center(child: CircularProgressIndicator()));
                }
                if (snapshot.hasData) {
                  return const HomeDashboard();
                }
                return const AuthScreen();
              },
            );
          }

          // Non-Firebase fallback: rely on AuthState provider.
          final auth = Provider.of<AuthState>(context);
          return auth.isSignedIn ? const HomeDashboard() : const AuthScreen();
        }),
        routes: {
          '/auth': (context) => const AuthScreen(),
          '/home': (context) => const HomeDashboard(),
          '/upload': (context) => const UploadScreen(),
          '/plan-builder': (context) => const PlanBuilderScreen(),
          '/flashcards': (context) => const FlashcardScreen(),
          '/exam': (context) => const ExamScreen(),
          '/public-plans': (context) => const PublicPlansScreen(),
          '/progress': (context) => const ProgressScreen(),
          '/settings': (context) => const SettingsScreen(),
          '/study-plan': (context) => const SizedBox.shrink(), // placeholder route for deep linking
        },
      ),
    );
  }
}
