name: educational_app
description: "A Grade12 Exam Prep Tutor (offline-first, testable Flutter app)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8

  # Core dependencies for Offline AI Tutor
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.5
  sqflite: ^2.3.3
  path: ^1.9.0
  syncfusion_flutter_pdf: ^31.1.19
  file_picker: ^10.3.3
  path_provider: ^2.0.15
  uuid: ^4.5.1
  awesome_notifications: ^0.10.1
  permission_handler: ^12.0.1
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2
  archive: ^4.0.7
  xml: ^6.5.0
  cloud_firestore: ^6.0.1
  flare_flutter: ^3.0.2
  google_sign_in: ^7.1.1
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  mockito: ^5.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/
